project:
  type: website
  output-dir: _site
  resources:
    - exploration.html
    - story.html

website:
  title: "Mind Over Music"
  description: "A visual history of Billboard Hot 100 genres."
  navbar:
    background: "#111827"
    foreground: "#f9fafb"
    left:
      - href: index.qmd
        text: Home
      - href: exploration.html
        text: Music through Change
      - href: story.html
        text: Music Mapped
      - href: project.qmd
        text: Explore the data
  page-footer:
    left: "Mind Over Music"
    right: "Built with Quarto"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true
